// Downloads each institution's icon from its official website into
// public/logos/<key>.<ext>, so the app never hot-links third-party images.
//   node scripts/fetch-logos.mjs            (only missing ones)
//   node scripts/fetch-logos.mjs --force    (re-download all)
// Order tried: the site's declared apple-touch-icon / icons (largest first),
// then /apple-touch-icon.png, then /favicon.ico, then Google's favicon cache.
import fs from "node:fs";
import path from "node:path";

export const LOGO_DOMAINS = {
  bdo: "bdo.com.ph",
  bpi: "bpi.com.ph",
  metrobank: "metrobank.com.ph",
  landbank: "landbank.com",
  pnb: "pnb.com.ph",
  securitybank: "securitybank.com",
  unionbank: "unionbankph.com",
  rcbc: "rcbc.com",
  chinabank: "chinabank.ph",
  eastwest: "eastwestbanker.com",
  gotyme: "gotyme.com.ph",
  maya: "maya.ph",
  cimb: "cimbbank.com.ph",
  tonik: "tonikbank.com",
  seabank: "seabank.ph",
  gcash: "gcash.com",
  grabpay: "grab.com",
  shopeepay: "shopee.ph",
  coinsph: "coins.ph",
  paypal: "paypal.com",
  pagibig: "pagibigfund.gov.ph",
  sss: "sss.gov.ph",
};

const OUT = path.resolve("public/logos");
const UA = { "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140 Safari/537.36" };
const force = process.argv.includes("--force");

const TYPES = { "image/png": "png", "image/x-icon": "ico", "image/vnd.microsoft.icon": "ico", "image/svg+xml": "svg", "image/jpeg": "jpg", "image/webp": "webp" };

async function get(url) {
  const res = await fetch(url, { headers: UA, redirect: "follow", signal: AbortSignal.timeout(15000) });
  if (!res.ok) throw new Error(`${res.status}`);
  return res;
}

function sniff(buf, contentType) {
  const head = buf.subarray(0, 12);
  if (head[0] === 0x89 && head[1] === 0x50) return "png";
  if (head[0] === 0 && head[1] === 0 && head[2] === 1) return "ico";
  if (head[0] === 0xff && head[1] === 0xd8) return "jpg";
  if (head.toString("ascii", 0, 4) === "RIFF") return "webp";
  if (/<svg/i.test(buf.subarray(0, 500).toString("utf8"))) return "svg";
  return TYPES[contentType?.split(";")[0]] ?? null;
}

async function candidates(domain) {
  const base = `https://www.${domain}`;
  const list = [];
  try {
    const res = await get(base);
    const html = await res.text();
    const finalUrl = res.url;
    for (const tag of html.match(/<link[^>]+>/gi) ?? []) {
      const rel = tag.match(/rel=["']([^"']+)["']/i)?.[1]?.toLowerCase() ?? "";
      if (!/icon/.test(rel) || /mask-icon/.test(rel)) continue;
      const href = tag.match(/href=["']([^"']+)["']/i)?.[1];
      if (!href) continue;
      const size = Number(tag.match(/sizes=["'](\d+)x\d+/i)?.[1] ?? (/apple-touch/.test(rel) ? 180 : /\.svg/i.test(href) ? 512 : 32));
      list.push({ url: new URL(href.replace(/&amp;/g, "&"), finalUrl).href, size });
    }
  } catch {}
  list.sort((a, b) => b.size - a.size);
  list.push({ url: `${base}/apple-touch-icon.png`, size: 180 }, { url: `https://${domain}/apple-touch-icon.png`, size: 180 }, { url: `${base}/favicon.ico`, size: 16 });
  // Last resort for sites that block scripted requests: Google's favicon cache (one-time download).
  list.push({ url: `https://www.google.com/s2/favicons?domain=${domain}&sz=128`, size: 128 });
  return list;
}

fs.mkdirSync(OUT, { recursive: true });
const report = [];
for (const [key, domain] of Object.entries(LOGO_DOMAINS)) {
  const existing = fs.readdirSync(OUT).find((f) => f.startsWith(key + "."));
  if (existing && !force) {
    report.push(`${key}: kept ${existing}`);
    continue;
  }
  let saved = null;
  for (const c of await candidates(domain)) {
    try {
      const res = await get(c.url);
      const buf = Buffer.from(await res.arrayBuffer());
      const ext = sniff(buf, res.headers.get("content-type"));
      if (!ext || buf.length < 200) continue;
      for (const f of fs.readdirSync(OUT).filter((f) => f.startsWith(key + "."))) fs.rmSync(path.join(OUT, f));
      fs.writeFileSync(path.join(OUT, `${key}.${ext}`), buf);
      saved = `${key}.${ext} (${buf.length} B, declared ${c.size}px) from ${c.url}`;
      break;
    } catch {}
  }
  report.push(`${key}: ${saved ?? "FAILED (the app shows a colored monogram instead)"}`);
}
console.log(report.join("\n"));

// Write the lookup the app imports (src/lib/logos.generated.ts).
const files = fs.readdirSync(OUT).filter((f) => /^[a-z0-9-]+\.(png|ico|svg|jpg|webp)$/.test(f)).sort();
fs.writeFileSync(
  path.resolve("src/lib/logos.generated.ts"),
  `// Generated by scripts/fetch-logos.mjs. Do not edit by hand.\nexport const LOGO_FILES: Record<string, string> = {\n${files
    .map((f) => `  ${JSON.stringify(f.replace(/\.[a-z]+$/, ""))}: "/logos/${f}",`)
    .join("\n")}\n};\n`,
);
console.log(`\nwrote src/lib/logos.generated.ts (${files.length} logos)`);
